update dasht-query-line and dasht-query-html to work with tsv
sunaku/dasht pull request #56
Opened 2021-07-29 15:09 UTC by smackesey

I extracted my work on TSV from the other Dash.app integration fork so that this could be separately merged. It follows your requests in #38.

2021-08-05 05:32 UTC, sunaku requested changes
Thanks for this PR.  I've requested some minor changes in the code review.

2021-08-05 05:32 UTC, sunaku commented on bin/dasht-query-line
> +# dasht-query-line - searches [Dash] docsets and emits results as tsv
Please uppercase "TSV".

2021-08-05 05:32 UTC, sunaku commented on bin/dasht-query-line
> +# and emits the results as TSV. However, if no results were found, this program
Please spell out "TSV" in prose: "as TSV" -> "in Tab Separated Vector (TSV) format"

2021-08-05 05:32 UTC, sunaku commented on bin/dasht-query-line
> +# Each search result is printed to stdout as a tab-separated line with fields:
The fields are separated, not the line; so "as a line with 4 tab-separated fields".

2021-08-05 05:32 UTC, sunaku commented on bin/dasht-query-line
> +      result[$1] = substr($0, index($0, $2) + length($2) + 1)
I would change the `index($0, $2)` call to `length($1) + 1` for robustness (no problem if `$1` contains `=`).

2021-08-05 05:32 UTC, sunaku commented on bin/dasht-query-line
> +      # print TSV line
I would drop this (redundant) comment.

2021-08-05 05:32 UTC, sunaku commented on bin/dasht-query-line
> +      printf "%s\t%s\t%s\t%s\n", result["name"], docset, \
I would add parentheses to the `printf()` call and list each argument on its own line.

2021-08-05 15:46 UTC, smackesey commented
Made the changes!

2021-08-26 06:09 UTC, sunaku requested changes
Thanks @smackesey!  I found some time to experiment with your latest changes and I would suggest applying the changes in the attached patch file in addition to my code review feedback.

* Attachment: [0001-beautify-and-clean-up-documentation.patch.txt](https://github.com/sunaku/dasht/files/7051979/0001-beautify-and-clean-up-documentation.patch.txt)

This PR is coming along nicely and we'll reach the finish line soon! :sweat_smile: Thanks for your patience.

2021-08-27 05:47 UTC, sunaku requested changes
Thanks for the update.  There's a potential AWK incompatibility that I've called out in the code review.  No worries about the patch file: I'll apply it on my side when I finally merge the PR. :nerd_face:

2021-08-27 05:58 UTC, sunaku requested changes

2021-08-28 05:08 UTC, sunaku commented
Looks great, thanks!  I'll try this out for a few days and let you know.  Overall, we should be good to merge. :+1:

2021-08-30 06:40 UTC, sunaku commented
Hi @smackesey, I found an issue when searching the BASH docset:

1. Before this PR
```
$ dasht 1 bash
digit-argument (M-0, M-1, … M--)  Bash function
PS1                               Bash variable
self-insert (a, b, A, 1, !, …)    Bash function
```

2. After this PR:
```
$ dasht 1 bash
digit-argument  (M-0, m-1,
PS1              Bash variable
self-insert       (a, b,
```

Following the first result link shows a `Can't load %E2%80%A6` error in w3m.

2021-08-30 16:03 UTC, smackesey commented
Fixed, the issue was that the `awk` field separator was still set to the default instead of tab. It didn't affect without spaces in the name, but screwed up those like the ones you posted. Sorry about that.

2021-10-02 20:37 UTC, sunaku commented
Sorry for the long delay. :sweat_smile: I'll merge this PR soon (ETA this week).

2021-10-30 14:34 UTC, sunaku commented
Merged in commit 49320bae5fc5e06a8fdf435d2e2101420f836a78. Thanks for your contribution :pray: and sorry for the long delay! :sweat_smile:

2021-10-30 14:34 UTC, closed without merging